name: NASA Project CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs: 
  build:
    env: 
      CI: true # runs workflow in CI env (disable watch mode for test)
      strategy: 
        matrix:
          node-version: [14.x, 16.x, 18.x]
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Use Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build --prefix client
      - run: npm test